---
# Ansible SSH鍵をAWS Secrets Managerから取得して配置

- name: Ensure .ssh directory exists
  file:
    path: "{{ home_dir }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: no

- name: Retrieve Ansible SSH key from AWS Secrets Manager
  command: >
    aws secretsmanager get-secret-value
    --secret-id {{ ansible_ssh_key_secret_name }}
    --region {{ ansible_ssh_key_region }}
    --query SecretString
    --output text
  register: ansible_ssh_key_secret
  changed_when: false
  no_log: true  # セキュリティ上、秘密情報をログに出力しない
  become: no

- name: Parse secret JSON
  set_fact:
    ansible_ssh_key_data: "{{ ansible_ssh_key_secret.stdout | from_json }}"
  no_log: true
  become: no

- name: Deploy Ansible SSH private key
  copy:
    content: "{{ ansible_ssh_key_data.private_key }}"
    dest: "{{ ansible_ssh_key_private_path }}"
    mode: "{{ ansible_ssh_key_private_mode }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  no_log: true
  become: no

- name: Deploy Ansible SSH public key
  copy:
    content: "{{ ansible_ssh_key_data.public_key }}"
    dest: "{{ ansible_ssh_key_public_path }}"
    mode: "{{ ansible_ssh_key_public_mode }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: no

- name: Verify private key permissions
  file:
    path: "{{ ansible_ssh_key_private_path }}"
    mode: "{{ ansible_ssh_key_private_mode }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: no

- name: Add SSH key to ssh-agent config (optional)
  blockinfile:
    path: "{{ home_dir }}/.ssh/config"
    create: yes
    mode: "0600"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Ansible SSH Key"
    block: |
      Host *
        AddKeysToAgent yes
        IdentityFile {{ ansible_ssh_key_private_path }}
  become: no
