---
- name: Install software-properties-common
  apt:
    name: software-properties-common
    state: present
    update_cache: yes

- name: Add Ansible PPA repository
  apt_repository:
    repo: ppa:ansible/ansible
    state: present

- name: Update apt cache after adding Ansible PPA
  apt:
    update_cache: yes

- name: Install Ansible
  apt:
    name: ansible
    state: present
